### ISSUE TITLE
Xperia X10 mini pro support

### ISSUE THREAD

**Issue by ipenburg** [vx/connectbot#1]
How hard would it be to add support for the X10 mini pro's hardware keyboard? I've got a rooted X10 mini pro and it seems like I can build the apk from this source, but I don't know if adding some mapping would require trail and error on the device to get the keycodes and then just put the X10 specific mapping in some java configuration resource? Where do I start with this issue?

**Comment by ipenburg** [comment]
With this limited keyboard: http://www.tech-freek.com/wp-content/uploads/2010/03/Xperia-X10-mini-pro.jpg

**Comment by mmatuska** [comment]
What keys are missing or should be reimplemented?
Do you have any experience with android SDK tools?

**Comment by non7top** [comment]
I also have the same device and here are some suggestions:
1. sym hardware key doesn't work
2. no up/down keys, I'd prefer volume keys to be used for that if possible, or [blue]+left/right, or may be onscreen keys

**Comment by mmatuska** [comment]
When you enable debug mode, what key number does the SYM key print?

**Comment by mmatuska** [comment]
I suppose you guys got a new phone by now :)
