### ISSUE TITLE
register "send to" intent

### ISSUE THREAD

**Issue by chrysn** [vx/connectbot#10]
picking files from the file system is atypical of android usage. i'd like to suggest that vx connectbot implement the ACTION_SEND an ACTION_SEND_MULTIPLE intents.

a typical use case would be having an image open in the gallery, and sending it to a laptop.

the server selection dialog that ensues when vx connectbot is selected for sending should list both non-connected and connected servers.

**Comment by mmatuska** [comment]
I am sorry but I don't have time and resources to implement this feature. Someone can do it, if he wants. The biggest problem is that files have to be send via byte streaming and not by OS file functions.
