### ISSUE TITLE
Merge Connectbot Bluetooth keyboard fix

### ISSUE THREAD

**Issue by inducer** [vx/connectbot#11]
Hi there,

there's a fix for an annoying issue that prevents many keys from working on BT keyboards, here:

https://code.google.com/p/connectbot/issues/detail?id=369 (comment 55)

Could you please apply it to vx connectbot? Thanks!

Andreas

**Comment by FaxMonkey** [comment]
Seconded!  Could really use that fix.  Bluetooth keyboard + vx connectbot + tablet would be perfect if control key worked.

**Comment by mmatuska** [comment]
Please try the new full hardware keyboard mode (as of v1.7.1-22 and higher).

**Comment by FaxMonkey** [comment]
On Nov 24, 2012, at 2:46 AM, Martin Matuška wrote:

> Please try the new full hardware keyboard mode.

APK available anywhere?

**Comment by FaxMonkey** [comment]
On Nov 24, 2012, at 11:54 AM, Martin Matuška wrote:

> Google Play

Trying to avoid that.

> or http://connectbot.vx.sk

Latest build available there is 1.7.1-21.

**Comment by FaxMonkey** [comment]
On Nov 24, 2012, at 1:04 PM, Martin Matuška wrote:

> Did you refresh the webpage? F5? There is 1.7.1-23

Got it, thank you!  And the full hardware keyboard mode did the trick, thanks VERY much!
