### ISSUE TITLE
Problems with Some Keys

### ISSUE THREAD

**Issue by ForeverOSS** [vx/connectbot#14]
I have just installed VX Connectbot to replace Connectbot on my Android phone and ran into an unexpected problem:

When I log in, my password is accepted without any problems, but when I use the keyboard  to enter the same password after a sudo command, I have to enter one of the characters in the Alt-section of the keyboard (< in this case), which is sent as ESC + 'd' to the other side instead of as '<'.

I just checked the keyboard and three characters in the Alt-section are not handled correctly, the middle dot, '<' and '>'.

**Comment by mmatuska** [comment]
What phone model do you have? Is it a physical or virtual keyboard?

**Comment by flat6** [comment]
I have the same problem. characters in the Alt-section of the keyboard '<' and '>' doesn't work using stock virtual keyboard (Archos 101 IT, Android 2.2) :

key ">" return "^[n"
key "<" return "^[b"

so it's not possible to redirect commands...
:-(
