### ISSUE TITLE
Cannot generate DSA keys

### ISSUE THREAD

**Issue by fpaquet** [vx/connectbot#16]
When trying to generate a DSA key, after giving a random seed, the app simply terminates the key generation dialogue immediately without generating any key.

We're using an asus eepad transformer TF201 with Android 4, latest VX ConnectBot.

**Comment by gsomgsomgsom** [comment]
I confirm this issue on android 4.0.4 on galaxy tab p5100.

**Comment by untitaker** [comment]
I confirm this issue with CyanogenMod 9 (Android 4.0.4) on HTC Wildfire.

**Comment by mmatuska** [comment]
I confirm this problem, too, seems to be a issue with Android 4.0 and later

**Comment by idealmundo** [comment]
Is this likely to be fixed, or is there a workaround? I need DSA keys to access my server. I have Droid Bionic with stock android 4.0.4.
