### ISSUE TITLE
Persist Connection does not work

### ISSUE THREAD

**Issue by AdmiralNemo** [vx/connectbot#21]
VX Connectbot does not stay running when switching activities, regardles of the state of the checkbox for persist connection. This makes it impossible to copy data from another app into a remote session (such as a one-time password) or to use the port forwarding options.

I have experienced this problem on my Motorola Droid 4 and my Asus Eee Pas Slider.

**Comment by AdmiralNemo** [comment]
Interestingly, this problem only seems to occur if both VX ConnectBot and the original ConnectBot are installed. As a workaround, I have uninstalled the original ConnectBot on both of my devices.

**Comment by supervacuo** [comment]
First Google result for "vx connectbot persist connections", and @AdmiralNemo's work-around is perfect! I also had both apps installed and was seeing VX connections dropped every time I switched apps; uninstalling the original ConnectBot resolved this issue.

**Comment by michael-ts** [comment]
I do not have the original ConnectBot installed and still have this problem . Please re-open.
