### ISSUE TITLE
Mosh support

### ISSUE THREAD

**Issue by kiranos** [vx/connectbot#22]
http://mosh.mit.edu/

"Mosh
(mobile shell)

Remote terminal application that allows roaming, supports intermittent connectivity, and provides intelligent local echo and line editing of user keystrokes.

Mosh is a replacement for SSH. It's more robust and responsive, especially over Wi-Fi, cellular, and long-distance links."

Here is some info about an android port: https://github.com/keithw/mosh/issues/32 from what I can gather they have a working client but they need someone to incorporate this into a connectbot, having vx connectbot support this would be awsome! 

First shell to support Mosh :D

**Comment by mmatuska** [comment]
Sorry, but I don't have the time and resources to implement this.

**Comment by leleobhz** [comment]
What can make Mosh support viable to implement?

**Comment by mmatuska** [comment]
The problem with Mosh vs Android is that there is no java client library available. The port https://github.com/ddrown/irssiconnectbot uses pre-compiled binaries so it's not compatible with all android devices.
