### ISSUE TITLE
RFE: Please add an option to disable Ctrl+<letter> shortcuts

### ISSUE THREAD

**Issue by fastcat** [vx/connectbot#24]
For me, it is far more useful to have things like Ctrl-d, Ctrl-w, Ctrl-c, etc. (on the hardware keyboard) go to the terminal and not be used as shortcuts within the application.  I realize that this may be quite different for other people, so I would suggest an option to have chorded Ctrl-<letter> presses always sent to the terminal.

**Comment by OliverUv** [comment]
Seconding this.

**Comment by balkian** [comment]
+1 It's the only reason I'll stick to irssi

**Comment by mmatuska** [comment]
Please try the Full hardware keyboard mapping in settings. This should work with bluetooth keyboards or other full-featured keyboards.

**Comment by OliverUv** [comment]
Enabling Full hardware keyboard mappings fixes this issue for the Asus TF300T Swedish keyboard. Thanks.
