### ISSUE TITLE
Serial Connection via USB OTG / Bluetooth

### ISSUE THREAD

**Issue by crami** [vx/connectbot#30]
It would be very nice if one would be able to use a USB to Serial adapter together with a USB OTG cable or a Bluetooth Serial Converter together with connectbot.

All other Serial Terminals available for Android are not as advanced as connectbot is!

**Comment by mmatuska** [comment]
Sorry, but I don't have the time and resources to implement this. That would require buying hardware and several hours of developing time. If someone wants to implement it, he is free to do so, I can merge his work after review.
