### ISSUE TITLE
Vx connectbot on Transformer Prime TP201

### ISSUE THREAD

**Issue by jmerge** [vx/connectbot#4]
Please add support for hardware keyboard for TP201.  In fact Vx connectbot works fine with Hackers Keyboard, but Hackers Keyboard must be loaded before connectbot, connectbot must be started with hw keyboard reattached. When ssh connection is established then I connect keyboard. Then SHIFT, TAB, CTRL, arrows work as on any other Windows or Linux box, function keys can be used as SHIFT+number which is perfect. But if connectbot crashes (which happens often when I have multiple ssh connections opened) then this keyboard functionality is lost, and whole process must be repeated.
Adding Hackers Keyboard functionality in Vx connectbot would be the best, but it would be great if functionality of Hackers Keyboard would automatically be restored with reloading.

**Comment by mmatuska** [comment]
The problem is I have no access to a TP201 where I could test it, therefore my debugging capabilities for this are limited.

**Comment by jmerge** [comment]
Let me know if I can help in any way. I made an error about function keys, they are achieved using Ctrl+number (not Shift+number).

**Comment by paulkoan** [comment]
Can I add a vote for the TF201 hardware keyboard.  It works perfectly in the main, the only difficulty is that the control key is intercepted.  So control-c does not send a break, but instead invokes `copy`.  Losing the control key is problematic in linux, and particularly if you use `gnu screen` as this uses `control-a` as a prefix to each command.  Having to tap the screen and then hit the ctrl icon is a shame when you have a keyboard right there.  Is there information I can provide that would help undersanding if or how the tf201 keyboard can be supported?

**Comment by mmatuska** [comment]
The CTRL key should work now on a TF201, but you cannot press the keys together (CTRL first, then letter)

**Comment by ematvey** [comment]
Is there any chance you could allow simultaneous CTRL+letter commands in settings? This behavior is the only reason I am reluctant to use VX.

**Comment by mmatuska** [comment]
Please try the new full hardware keyboard mode as of version 1.7.1-22 and later.
