### ISSUE TITLE
Can't select from sym menu by physical keyboard

### ISSUE THREAD

**Issue by anounyym1** [vx/connectbot#44]
Looks like I can't select from sym window any character by physical keyboard. Every keypress goes straight to current connection, like arrows or enter. 

EDIT: There is something broken with github for me as I can't comment anything, but it works for me now with version 1.7.1-24, Android 4.1.1 (paranoidandroid) and physical keyboard.

**Comment by kenta2** [comment]
I can confirm this bug.  I cannot select text for clipboard copy using the D pad.  This behavior can also be seen with the Hacker's Keyboard virtual keyboard 5-line layout which has a virtual D pad (arrow keys) .  Irssi connectbot does not have this bug.

**Comment by anounyym1** [comment]
Looks working now, thanks!

**Comment by kenta2** [comment]
This issue still persists in version 1.71.1-24 on Android 4.1 and Android 4.2.

**Comment by anounyym1** [comment]
It works for me with version 1.7.1-24, Android 4.1.1 (paranoidandroid) and physical keyboard.

**Comment by anounyym1** [comment]
It works for me with version 1.7.1-24, Android 4.1.1 (paranoidandroid) and physical keyboard.

**Comment by anounyym1** [comment]
It works for me with version 1.7.1-24, Android 4.1.1 (paranoidandroid) and physical keyboard.
