### ISSUE TITLE
vxconnectbot can't forward any port (local)

### ISSUE THREAD

**Issue by billerr** [vx/connectbot#5]
Hi. I have VXconnectbot installed on an HTC Desire GSM. My remote SSH server is located behind a router, port 22 properly forwarded and all.

I have SSH access (password- and key-based) alright, but the local port forwards associated to my host entry can never be enabled. I tried with a Wi-Fi and 3G connection (to eliminated speed issues), same problem. I even tried from within the same LAN, still nothing. I can enable local port forwards with an ssh command through the standard Terminal Emulator and through the SSHtunnel app (they only support password-based logins, though). The ports I've tried forwarding (same for source and destination) are 9091, 49152, 8080, 9, 3389. No luck with any of them, they always return the same standard error "Problem creating port forward...". I couldn't find any solution online.

Looking through the source, I found that the LocalAcceptThread version using INetSocketAddress is used for enabling port forwards. Perhaps if it was changed to the LocalAcceptThread that's using a simple int for the port, forwards might not fail. Tell me what more info I can give you to troubleshoot the problem, as I like VxConnectBot a lot, and I'd hate to use an alternative.

Thanks!
Bill

**Comment by mmatuska** [comment]
Hi, that is quite strange. I have absolutely no problems with port forwards from my SE Xperia Pro, I use it to forward RDP, VNC, HTTP, etc. Can you give me more information? Did you properly configure the port forwarding?

**Comment by billerr** [comment]
Well it appears to have been a ROM problem. I change ROM this weekend, and it works like magic.
Sorry for bothering you! Keep up the great work!
