### ISSUE TITLE
enhancement: Autorun command on boot/scheduler.

### ISSUE THREAD

**Issue by kamathln** [vx/connectbot#56]
Allow to run commands on boot (at least on the "local" host - the phone/tablet itself). My specific requirement is to bring up Apache, SSH server from my debian partition on the SD card. 

But I can see innumerable potential uses that others can make out of it - auto backup of information from phone using custom scripts, checking remote servers, killing unnecessary processes, etc. 

I also wonder what is possible with this+ Android commands like am,getprop/setprop, etc.

**Comment by fastcat** [comment]
Somehow I don't think this is what connectbot is for ... try SManager
