### ISSUE TITLE
Fullscreen setting removal breaks landscape functionality

### ISSUE THREAD

**Issue by okossuth** [vx/connectbot#61]
hi

After updating vxconnectbot the last version on my xperia arc s, im now unable to use it in landscape mode. The virtual keyboard now hides the console text so im unable to use the program effectively. I found out that the fullscreen setting was removed 4 months ago:
https://github.com/vx/connectbot/commit/1def84ce9f26a0a2bab0f6ad8fc15f386616a77b
 I used this setting to make landscape work on my smartphone. Is it possible to bring back that feature? or download an old release of vxconnectbot??
thanks

**Comment by mmatuska** [comment]
Please try the latest beta version from http://connectbot.vx.sk - it doesn't use ActionBarWrapper anymore

**Comment by okossuth** [comment]
thanks
