### ISSUE TITLE
Unable to login after update to v.25

### ISSUE THREAD

**Issue by fidelleon** [vx/connectbot#66]
After updating from v.20 to v.25 (both via Google Play and direct APK installation), I'm unable to connect to two Linux boxes (both running Ubuntu 13.10). 

Downgrading to v.20 (or using the original ConnectBot) works always okay, so I can rule it's not a network connectivity issue.

No errors, no crashes, nothing, simply a "Connecting to xxxxxx:22..." for minutes.

**Comment by mmatuska** [comment]
Does it work with v24:
http://connectbot.vx.sk/download/vx-connectbot-1.7.1-24.apk

Have you also tried resetting your settings?
What Android version are you using?

**Comment by fidelleon** [comment]
Thanks for your reply. 

Just installed v.24, works like a charm!

Yes, one of the first things I did was nuking all my settings (in fact, full uninstall and direct v.25 installation from Google Play). All my server logs show is:

sshd[6861]: Connection closed by 192.168.1.193 [preauth]

I'm running CyanogenMod 7 (Android v2.3.7) on a Sony Ericsson Xperia Neo.

**Comment by levaidaniel** [comment]
Same here with Android 2.2.2 and VX ConnectBot 1.7.1-25.
The symptoms are the same both on the client and the server.

Daniel

**Comment by mmatuska** [comment]
Looks like it doesn't work with Android 2.3 anymore, I will pull back v25 and release v26 for 4.0+ only shortly

**Comment by fidelleon** [comment]
Oh, okay, looks like time to upgrade to Jelly Bean... BTW, here you have my full debug log from my connection attempts: http://pastebin.com/HnxYDvnE

**Comment by mmatuska** [comment]
I have reverted version 26 to the state of version 24 and stopped supporting Android 2.x with 1.7.1-26
New version 1.7.1-27 requires at least API 11 (Honeycomb, Android 3.0)
